from tkinter import *
from tkinter import ttk
from tkinter import filedialog
from tkinter import scrolledtext

class Root(Tk):
    def __init__(self):

        super(Root, self).__init__()
        
        self.geometry("1920x1051+650+150")
        self.title("Voice-Based Programming")
        self.configure(background="#374046")
        self.attributes('-fullscreen', True)  
        
        self.SelectFile = Button()
        self.SelectFile.place(relx=0.057, rely=0.447, height=133, width=486)
        self.SelectFile.configure(activebackground="#ff9100")
        self.SelectFile.configure(activeforeground="#000000")
        self.SelectFile.configure(background="#ff9100")
        self.SelectFile.configure(disabledforeground="#bfbfbf")
        self.SelectFile.configure(font="-family {JetBrains Mono} -size 12 -weight normal -slant roman -underline 0 -overstrike 0")
        self.SelectFile.configure(foreground="#ffffff")
        self.SelectFile.configure(highlightbackground="#ffffff")
        self.SelectFile.configure(highlightcolor="black")
        self.SelectFile.configure(pady="0")
        self.SelectFile.configure(relief="flat")
        self.SelectFile.configure(text='''Open Current File''')
        
        self.OpenFile = Button()
        self.OpenFile.place(relx=0.057, rely=0.609, height=133, width=486)
        self.OpenFile.configure(activebackground="#ff9100")
        self.OpenFile.configure(activeforeground="#000000")
        self.OpenFile.configure(background="#ff9100")
        self.OpenFile.configure(disabledforeground="#bfbfbf")
        self.OpenFile.configure(font="-family {JetBrains Mono} -size 12 -weight normal -slant roman -underline 0 -overstrike 0")
        self.OpenFile.configure(foreground="#ffffff")
        self.OpenFile.configure(highlightbackground="#ffffff")
        self.OpenFile.configure(highlightcolor="black")
        self.OpenFile.configure(pady="0")
        self.OpenFile.configure(relief="flat")
        self.OpenFile.configure(text='''Select New File''')
        
        self.Exit = Button()
        self.Exit.place(relx=0.057, rely=0.771, height=133, width=486)
        self.Exit.configure(activebackground="#ff9100")
        self.Exit.configure(activeforeground="#000000")
        self.Exit.configure(background="#ff9100")
        self.Exit.configure(disabledforeground="#bfbfbf")
        self.Exit.configure(font="-family {JetBrains Mono} -size 12 -weight normal -slant roman -underline 0 -overstrike 0")
        self.Exit.configure(foreground="#ffffff")
        self.Exit.configure(highlightbackground="#ffffff")
        self.Exit.configure(highlightcolor="black")
        self.Exit.configure(pady="0")
        self.Exit.configure(relief="flat")
        self.Exit.configure(text='''Exit''')

        self.Listen = Button()
        self.Listen.place(relx=0.057, rely=0.095, height=133, width=486)
        self.Listen.configure(activebackground="#ff9100")
        self.Listen.configure(activeforeground="#000000")
        self.Listen.configure(background="#ff9100")
        self.Listen.configure(disabledforeground="#bfbfbf")
        self.Listen.configure(font="-family {JetBrains Mono} -size 12 -weight normal -slant roman -underline 0 -overstrike 0")
        self.Listen.configure(foreground="#ffffff")
        self.Listen.configure(highlightbackground="#ffffff")
        self.Listen.configure(highlightcolor="black")
        self.Listen.configure(pady="0")
        self.Listen.configure(relief="flat")
        self.Listen.configure(text='''Start Listening...''')
        
        self.Scrolledtext = scrolledtext.ScrolledText()
        self.Scrolledtext.place(relx=0.496, rely=0.133, relheight=0.772, relwidth=0.467)
        self.Scrolledtext.configure(background="white")
        self.Scrolledtext.configure(font="-family {JetBrains Mono} -size 12 -weight normal -slant roman -underline 0 -overstrike 0")
        self.Scrolledtext.configure(foreground="black")
        self.Scrolledtext.configure(highlightbackground="#ffffff")
        self.Scrolledtext.configure(highlightcolor="black")
        self.Scrolledtext.configure(insertbackground="black")
        self.Scrolledtext.configure(insertborderwidth="3")
        self.Scrolledtext.configure(selectbackground="blue")
        self.Scrolledtext.configure(selectforeground="white")
        self.Scrolledtext.configure(wrap="none")
        self.Scrolledtext.insert('end', 'def hello_world():\n\tprint("Hello World")\n\nhello_world()')
        self.Scrolledtext.configure(state=DISABLED)

        self.TSeparator1 = ttk.Separator()
        self.TSeparator1.place(relx=0.435, rely=0.048, relheight=0.905)
        self.TSeparator1.configure(orient="vertical")
        
        self.TSeparator2 = ttk.Separator()
        self.TSeparator2.place(relx=0.061, rely=0.39, relwidth=0.302)

        self.Label1 = Label()
        self.Label1.place(relx=0.057, rely=0.257, height=75, width=482)
        self.Label1.configure(background="#374046")
        self.Label1.configure(disabledforeground="#bfbfbf")
        self.Label1.configure(font="-family {JetBrains Mono} -size 12 -weight normal -slant roman -underline 0 -overstrike 0")
        self.Label1.configure(foreground="#ff8a65")
        self.Label1.configure(text='''Do Not Speak...''')

        self.Label2 = Label()
        self.Label2.place(relx=0.461, rely=0.057, height=46, width=802)
        self.Label2.configure(background="#374046")
        self.Label2.configure(disabledforeground="#bfbfbf")
        self.Label2.configure(font="-family {JetBrains Mono} -size 12 -weight normal -slant roman -underline 0 -overstrike 0")
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(text='''See Your Code Here''')
    

root = Root()
root.mainloop()